Fix China AZs
giantswarm/kubectl-gs pull request #335
Opened 2021-05-07 11:32 UTC by paurosello

China only has 2 AZs so we should open this a bit. In other regions, although we do not recommend it, 2AZ also works

2021-05-07 11:35 UTC, calvix approved these changes
lgtm if tested

2021-05-07 11:36 UTC, axbarsan requested changes

2021-05-07 11:36 UTC, axbarsan commented on cmd/template/cluster/flag.go
> +			if len(f.MasterAZ) < 1 && len(f.MasterAZ) > 3 {
Not sure if the length can be both less than 1 and more than 3 at the same time 😬 

```suggestion
			if len(f.MasterAZ) < 1 || len(f.MasterAZ) > 3 {
```

2021-05-07 11:37 UTC, axbarsan commented
Please don't forget about updating `CHANGELOG.md` 👍🏻

2021-05-07 12:02 UTC, anvddriesch commented
LGTM!
Just make sure this works correctly with 3 AZ names showing up in the CR like this:
```
availabilityZones:
- AZ1
- AZ2
- AZ2
```

2021-05-10 07:17 UTC, paurosello commented
> LGTM!
> Just make sure this works correctly with 3 AZ names showing up in the CR like this:
> 
> ```
> availabilityZones:
> - AZ1
> - AZ2
> - AZ2
> ```

Oh true! we should not allow 2 AZ, just enable repeating AZ as the master needs to be either 1 or 3 always

2021-05-10 07:33 UTC, axbarsan approved these changes
LGTM after fixing CI 🌟

2021-05-11 10:25 UTC, merged